# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotted" do
  name "spotted"
  desc "Unofficial CLI for the Spotify API"
  homepage "https://spotted.stldocs.com/"
  version "0.18.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotted"
  manpage "man/man1/spotted.1.gz"
  bash_completion "completions/spotted.bash"
  zsh_completion "completions/spotted.zsh"
  fish_completion "completions/spotted.fish"

  on_macos do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_amd64.zip"
      sha256 "19c6e1445b1be7170ac2032bd1249cddb248354d554f60f3ef49e4206933dac6"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_arm64.zip"
      sha256 "af0fa3d2d587a27409b366f496657cf1151e1a4aef50a28f27a7abf876fb392c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_amd64.tar.gz"
      sha256 "76176b2f1cbf2a7ed8bf00da32d075c1f63d22d87c9c13f734c467d673e294b3"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_arm64.tar.gz"
      sha256 "e78070f5335babaf43e30bdb1b6202e26acefb243352f5037901f0b472cc9f79"
    end
  end

  # No zap stanza required
end
