# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotted" do
  name "spotted"
  desc "Unofficial CLI for the Spotify API"
  homepage "https://spotted.cjav.dev/"
  version "0.22.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotted"
  manpage "man/man1/spotted.1.gz"
  bash_completion "completions/spotted.bash"
  zsh_completion "completions/spotted.zsh"
  fish_completion "completions/spotted.fish"

  on_macos do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_amd64.zip"
      sha256 "a0be6b8d517477ffa2e98cd6753b854151999df5ee72d5d349f8830342cd6ce5"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_arm64.zip"
      sha256 "9c531cd3ffe1e461acd1c4686ed1b705f845b7ff732279d43bcb5f392b70673b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_amd64.tar.gz"
      sha256 "633235191fc9096c782027da257fb4c8412bafca20ae5573ec64bab62db13585"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_arm64.tar.gz"
      sha256 "ccb8975c8ddff9c592c6867c25209d86931d4f009015f038c311633579b17dc5"
    end
  end

  # No zap stanza required
end
