# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotted" do
  name "spotted"
  desc "Unofficial CLI for the Spotify API"
  homepage "https://spotted.cjav.dev/"
  version "0.23.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotted"
  manpage "man/man1/spotted.1.gz"
  bash_completion "completions/spotted.bash"
  zsh_completion "completions/spotted.zsh"
  fish_completion "completions/spotted.fish"

  on_macos do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_amd64.zip"
      sha256 "784faaf5b15bb8893c5bc20dea8db078dcb9347383dd5fe7c42b40bda4da0ed3"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_macos_arm64.zip"
      sha256 "51878511c84e131194970f3802588663a36535bcfac419439ea06fcbcd68eda8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_amd64.tar.gz"
      sha256 "022dc7fdf43f14c0c826c2683f2980ed35ee32e13e0f433db8ca55e5331c87ae"
    end
    on_arm do
      url "https://github.com/cjavdev/spotted-cli/releases/download/v#{version}/spotted_#{version}_linux_arm64.tar.gz"
      sha256 "9417d7579dc6d6b5be150f05205c56fc713b2d396fb86619cb781abf7c9191f2"
    end
  end

  # No zap stanza required
end
